version: "3.8"
services:
  notes-app:
    build:
      context: .
    ports:
      - '4000:4000'
    environment:
      DB_HOST: postgres
    volumes:
      - ./public:/opt/notes-app/public
      - ./scripts:/opt/notes-app/scripts
      - ./server:/opt/notes-app/server
      - ./src:/opt/notes-app/src

volumes:
  db:
